repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.0
    hooks:
      - id: cspell
        types:
          - python
          - markdown

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: ruff check
        name: ruff check
        language: system
        entry: uv run -- ruff check
        files: ^.*\.py$

      - id: ruff format
        name: ruff format
        language: system
        entry: uv run -- ruff format
        files: ^.*\.py$

      - id: mypy
        name: mypy
        language: system
        entry: uv run -- mypy -p dlc
        pass_filenames: false
        files: ^.*\.py$
