name: Test

on:
  # Run at 00:00 on Monday or manual trigger
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch: # Allows manual triggering
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false # Continue with other versions if one fails

    name: Test using Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run tests
        run: uv run -- pytest -vv --cov=dlc --cov-report=xml
